# Generated by Django 6.0.2 on 2026-03-13 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0002_plan_notificacion_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
