# Generated by Django 6.0.2 on 2026-03-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0003_aplicacion_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='estado_validacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('aspirante', 'Aspirante'), ('empresa', 'Empresa'), ('validador', 'Validador')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
