# Generated by Django 6.0.2 on 2026-03-27 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0004_vacante_estado_validacion_alter_usuario_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(blank=True, help_text='Ej. Desarrollador Frontend, Data Scientist', max_length=150, null=True)),
                ('experiencia_resumen', models.TextField(blank=True, null=True)),
                ('cv_url', models.URLField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('habilidades', models.JSONField(blank=True, default=list, help_text='Lista de tecnologías que domina')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aspirante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aspirantes',
            },
        ),
    ]
