# Generated by Django 6.0.2 on 2026-03-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0005_aspirante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='cv_url',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='aspirante',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
