# Generated by Django 6.0.2 on 2026-03-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0006_remove_aspirante_cv_url_remove_aspirante_foto_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tecnologias',
            },
        ),
    ]
